# Docker Image Build and Deploy Workflow
name: Docker Image Build and Deploy

env:
  # Registry Docker où seront stockés les images
  REGISTRY: abellus/demo1 
  # Nom de l'image qui sera construit
  IMAGE_NAME: ${{ github.repository }}

on:
  # Déclenchement sur push dans la branche main
  push:
    branches:
      - main
  # Déclenchement sur pull request dans la branche main 
  pull_request: 
    branches:
      - main

  # Définition du job
jobs:
  # Système d'exploitation de la machine virtuelle
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Etape : récupération du dépôt
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Etape : authentification sur le registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      # Etape : construction et push de l'image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/demo:latest .
          docker push ${{ env.REGISTRY }}/${{ github.repository_owner }}/demo:latest

      # Etape : déploiement sur Heroku
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "devops_data_collection" 
          heroku_email: "bellomay14@gmail.com"