#Nom du Workflow : Docker Image CI
name: Docker Image CI

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: abellus/demo1
  IMAGE_NAME: ${{ github.repository }}

#Spécifie les évènements qui déclenchent le Workflow
on:
#Par un push sur la branche main
  push:
    branches: [ "main" ]
#Ou par un pull_request sur la branche main
  pull_request:
    branches: [ "main" ]

#Contenir la liste des taches a exécuter
jobs:
  # La tache build
  build:
    # On spécifie L'OS(ubuntu-latest) de la machine virtuel ou la tâche doit s'executer 
    runs-on: ubuntu-latest
    #Lister les étapes du job "build"
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      # Etape ou est executer la commande qui permet de construire l'image Docker
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.REGISTRY }}:latest
    - name: Log into registry ${{ env.REGISTRY }}
      run: docker login -u ${{ secrets.DOCKHERHUB_USERNAME }} -p ${{ secrets.DOCKHERHUB_TOKEN }}
    - name: Push Docker image
      run: docker push ${{ env.REGISTRY }}:latest

